# Generated by Django 5.1.7 on 2025-06-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='available_locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
