# Generated by Django 5.1.7 on 2025-07-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_available_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='new', max_length=20),
        ),
    ]
