# Generated by Django 5.1.7 on 2025-07-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_supplier_deleted_at_supplier_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
