# Generated by Django 5.1.7 on 2025-06-16 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_paymentmethod_bookingitem_due_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_luggage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
