# Generated by Django 5.1.7 on 2025-06-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_contact_info_alter_booking_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(default='SAMPLE', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
