# Generated by Django 5.1.7 on 2025-06-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(choices=[('vnd', 'Vnd'), ('usd', 'Usd')], default='vnd', max_length=3),
        ),
    ]
