# Generated by Django 5.1.7 on 2025-06-22 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_paymentmethod_id_alter_bookingitem_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.ForeignKey(db_column='payment_method_type', default='credit_card', on_delete=django.db.models.deletion.CASCADE, to='booking.paymentmethod'),
            preserve_default=False,
        ),
    ]
