# Generated by Django 5.1.7 on 2025-06-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_payment_type_booking_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
