# Generated by Django 5.1.7 on 2025-06-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_booking_payment_method_delete_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_confirmed_to_cancellation_policy',
            field=models.BooleanField(default=False),
        ),
    ]
