# Generated by Django 5.1.7 on 2025-07-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingeventhistory',
            old_name='message',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bookingeventhistory',
            old_name='metadata',
            new_name='value',
        ),
        migrations.AddField(
            model_name='bookingeventhistory',
            name='instance_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
