# Generated by Django 5.1.7 on 2025-07-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_rename_message_bookingeventhistory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingeventhistory',
            name='instance_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
