# Generated by Django 5.1.7 on 2025-06-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_available_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='service_type',
            field=models.CharField(choices=[('airport_transfer', 'Airport Transfer'), ('fast_track', 'Fast Track'), ('e_visa', 'E Visa')], max_length=20),
        ),
    ]
