# Generated by Django 5.1.7 on 2025-07-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='what_nexts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
