# Generated by Django 5.1.7 on 2025-07-15 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_max_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('adjustment_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=32)),
                ('adjustment_value', models.JSONField(blank=True, null=True)),
                ('time_range_type', models.CharField(choices=[('period', 'Period'), ('recurring_day_of_week', 'Recurring Day Of Week'), ('recurring_day_of_month', 'Recurring Day Of Month')], default='period', max_length=32)),
                ('time_range_value', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, related_name='price_configs', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
