# Generated by Django 5.1.7 on 2025-07-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productpriceconfiguration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_usd',
            new_name='base_price_usd',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_vnd',
            new_name='base_price_vnd',
        ),
    ]
