# Generated by Django 5.1.7 on 2025-07-18 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_price_usd_product_base_price_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailabilityconfiguration',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productavailabilityconfiguration',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
