# Generated by Django 5.1.7 on 2025-07-16 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_price_usd_product_base_price_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailabilityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('block', 'Block'), ('no_limit', 'No Limit'), ('fixed_quantity', 'Fixed Quantity'), ('percentage_quantity', 'Percentage Quantity')], max_length=255)),
                ('value', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('products', models.ManyToManyField(blank=True, related_name='availability_configurations', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
