# Generated by Django 5.1.7 on 2025-07-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productavailabilityconfiguration_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailabilityconfiguration',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
