# Generated by Django 5.1.7 on 2025-07-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productavailabilityconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailabilityconfiguration',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
