# Generated by Django 5.1.7 on 2025-07-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productavailabilityconfiguration_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productavailabilityconfiguration',
            name='code',
        ),
    ]
