# Generated by Django 5.1.7 on 2025-07-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productavailabilityconfiguration_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productavailabilityconfiguration',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='availability_configs', to='product.product'),
        ),
    ]
