# Generated by Django 5.1.7 on 2025-07-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='article',
            name='content_vi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='article',
            name='title_vi',
            field=models.CharField(default='vietnam', max_length=255),
            preserve_default=False,
        ),
    ]
