# Generated by Django 5.1.7 on 2025-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_rename_content_article_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_vi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
