# Generated by Django 5.1.7 on 2025-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_alter_article_content_en_alter_article_content_vi'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='product_ids',
            field=models.JSONField(default=list),
        ),
    ]
