# Generated by Django 5.1.7 on 2025-07-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_article_product_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_vi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
