# Generated by Django 5.1.7 on 2025-06-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
