# Generated by Django 5.1.7 on 2025-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
