# Generated by Django 5.1.7 on 2025-06-16 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_paymentmethod_bookingitem_due_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=32)),
                ('note', models.TextField(blank=True, null=True)),
                ('total_applicants', models.IntegerField(default=1)),
                ('total_completed_applicants', models.IntegerField(default=0)),
                ('total_incomplete_applicants', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EVisaApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=32)),
                ('data', models.JSONField()),
                ('evisa_truth_acknowledgement_and_fee_policy_agreement', models.BooleanField(default=False)),
                ('passport_image_url', models.URLField(blank=True, null=True)),
                ('portrait_image_url', models.URLField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.evisaapplication')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
